language: go

go:
  - 1.6.2

before_script:
  - go get github.com/mitchellh/gox
  - go vet github.com/dropbox/dbxcli

script: >
  gox -ldflags="-s -w -X main.version=${TRAVIS_TAG:-TRAVIS_COMMIT}"
  -osarch="darwin/amd64 linux/amd64 windows/amd64"
  -output "dist/{{.Dir}}-{{.OS}}-{{.Arch}}"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "dist/*"
  file_glob: true
  on:
    tags: true
